// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMRlSIIBY7qlUtZHY31FrGV_rx4hpIj0g',
    appId: '1:644706345304:web:0b9049c5f0cef1f451452d',
    messagingSenderId: '644706345304',
    projectId: 'bmicalculator-add06',
    authDomain: 'bmicalculator-add06.firebaseapp.com',
    storageBucket: 'bmicalculator-add06.appspot.com',
    measurementId: 'G-EW7ZE05R38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl6agOGgT1Ww8yKrivrrBUCQSic-15xJ8',
    appId: '1:644706345304:android:a484335f7625882051452d',
    messagingSenderId: '644706345304',
    projectId: 'bmicalculator-add06',
    storageBucket: 'bmicalculator-add06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzsA7gNFEcg0zNPhwUUmOf-qwNxZzG1x8',
    appId: '1:644706345304:ios:3b7340bf0d89c85251452d',
    messagingSenderId: '644706345304',
    projectId: 'bmicalculator-add06',
    storageBucket: 'bmicalculator-add06.appspot.com',
    iosClientId: '644706345304-m0bmump32d3l44lph9b1jedapt5l9jk1.apps.googleusercontent.com',
    iosBundleId: 'com.codedady.bmiCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzsA7gNFEcg0zNPhwUUmOf-qwNxZzG1x8',
    appId: '1:644706345304:ios:3b7340bf0d89c85251452d',
    messagingSenderId: '644706345304',
    projectId: 'bmicalculator-add06',
    storageBucket: 'bmicalculator-add06.appspot.com',
    iosClientId: '644706345304-m0bmump32d3l44lph9b1jedapt5l9jk1.apps.googleusercontent.com',
    iosBundleId: 'com.codedady.bmiCalculator',
  );
}
